name: hausify_v2
description: "Hausify Version 2"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


# ------------PACKAGES-------------
dependencies:
  flutter:
    sdk: flutter

  # UTILITY PACKAGES

  # ICONS
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # STATE MANAGEMENT
  get: ^4.6.6
  flutter_native_splash: ^2.4.0

  # PRODUCT SPECIFIC


# ------------PACKAGES END-------------

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # ------------LOCAL ASSETS-------------
  assets:
    - assets/icons/
    - assets/images/
    - assets/logos/


  # ------------LOCAL FONTS--------------
  #fonts:
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
