// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzC-S0Das7Z5yQkeTA0WyZFzV2uue4LB0',
    appId: '1:841765738097:web:bcf2b21df2815d9320add0',
    messagingSenderId: '841765738097',
    projectId: 'ecommerceapp-c1f6f',
    authDomain: 'ecommerceapp-c1f6f.firebaseapp.com',
    storageBucket: 'ecommerceapp-c1f6f.appspot.com',
    measurementId: 'G-NKNB4LNWT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9p1k2MfUzArqPSbBRT538kU-jltVBLcs',
    appId: '1:841765738097:android:45512e076a01d17220add0',
    messagingSenderId: '841765738097',
    projectId: 'ecommerceapp-c1f6f',
    storageBucket: 'ecommerceapp-c1f6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL9ieEKLv88xUmOBU-4U1_9Lz2sluwwVQ',
    appId: '1:841765738097:ios:c2e4feb5cf306dc120add0',
    messagingSenderId: '841765738097',
    projectId: 'ecommerceapp-c1f6f',
    storageBucket: 'ecommerceapp-c1f6f.appspot.com',
    androidClientId: '841765738097-88r5hb624usdoma44bugkhipdc1v0cl0.apps.googleusercontent.com',
    iosClientId: '841765738097-t7prn2l208vsk18j3ks7fguoob4h2b0v.apps.googleusercontent.com',
    iosBundleId: 'com.hausifyv2.hausifyV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL9ieEKLv88xUmOBU-4U1_9Lz2sluwwVQ',
    appId: '1:841765738097:ios:c2e4feb5cf306dc120add0',
    messagingSenderId: '841765738097',
    projectId: 'ecommerceapp-c1f6f',
    storageBucket: 'ecommerceapp-c1f6f.appspot.com',
    androidClientId: '841765738097-88r5hb624usdoma44bugkhipdc1v0cl0.apps.googleusercontent.com',
    iosClientId: '841765738097-t7prn2l208vsk18j3ks7fguoob4h2b0v.apps.googleusercontent.com',
    iosBundleId: 'com.hausifyv2.hausifyV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzC-S0Das7Z5yQkeTA0WyZFzV2uue4LB0',
    appId: '1:841765738097:web:afb690fae463eee120add0',
    messagingSenderId: '841765738097',
    projectId: 'ecommerceapp-c1f6f',
    authDomain: 'ecommerceapp-c1f6f.firebaseapp.com',
    storageBucket: 'ecommerceapp-c1f6f.appspot.com',
    measurementId: 'G-STPKLLWTTY',
  );

}